package com.ktv303.numeric;

public enum RomanNumbers 
{
	I , II, III, IV, V, VI, VII, VIII, IX, X, 											//1 - 10
	XI, XII, XIII, XIV, XV, XVI, XVII, XVIII, XIX, XX,									//11 - 20
	XXI, XXII, XXIII, XXIV, XXV, XXVI, XXVII, XXVIII, XXIX, XXX,						//21 - 30
	XXXI, XXXII, XXXIII, XXXIV, XXXV, XXXVI, XXXVII, XXXVIII, XXXIX, XL,				//31 - 40
	XLI, XLII, XLIII, XLIV, XLV, XLVI, XLVII, XLVIII, XLIX, L,							//41 - 50
	LI, LII, LIII, LIV, LV, LVI, LVII, LVIII, LIX, LX,									//51 - 60
	LXI, LXII, LXIII, LXIV, LXV, LXVI, LXVII, LXVIII, LXIX, LXX,						//61 - 70
	LXXI, LXXII, LXXIII, LXXIV, LXXV, LXXVI, LXXVII, LXXVIII, LXXIX, LXXX,				//71 - 80
	LXXXI, LXXXII, LXXXIII, LXXXIV, LXXXV, LXXXVI, LXXXVII, LXXXVIII, LXXXIX, XC,		//81 - 90
	XCI, XCII, XCIII, XCIV, XCV, XCVI, XCVII, XCVIII, XCIX, C							//91 - 100
}
